retail_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "UFNPKVG-OKC98299"        
      user: "SAIROHITH"              
      password: "SRRNagella1998$"     
      role: "ACCOUNTADMIN"                 
      warehouse: "COMPUTE_WH"
      database: "RETAIL_PROJECT"
      schema: "RAW"                    
      threads: 4
      client_session_keep_alive: False
