
version: 2

models:
  - name: dim_stores
    description: "stores details model"
    columns:
      - name: store_id
      - name: location
      - name: Region
      - name: store_manager
      - name: open_date
      - name: store_type
      - name: days_since_opening
      - name: store_age_category
      - name: store_category
      - name: is_new_store
      - name: etl_loaded_at


